const proposals = [
  {
    name: "BrazilQ42021",
    payment_amount: 110,
    url: "https://www.dashcentral.org/p/DashBrazilQ42021",
    AbsoluteYesCount: 606,
    YesCount: 810,
    NoCount: 204,
    AbstainCount: 42,
    fCachedEndorsed: false,
    fCachedFunding: true,
    passing: true,
    pastTrigger: true,
  },
  {
    name: "dash-incubator-2021-q4",
    payment_amount: 500,
    url: "https://www.dashcentral.org/p/dash-incubator-2021-q4",
    AbsoluteYesCount: 405,
    YesCount: 412,
    NoCount: 7,
    AbstainCount: 1,
    fCachedEndorsed: false,
    fCachedFunding: false,
    passing: false,
    pastTrigger: false,
  },
  {
    name: "Scoby-Society-investment",
    payment_amount: 540.6,
    url: "https://www.dashcentral.org/p/Scoby-Society-investment",
    AbsoluteYesCount: -121,
    YesCount: 79,
    NoCount: 200,
    AbstainCount: 60,
    fCachedEndorsed: false,
    fCachedFunding: false,
    passing: false,
    pastTrigger: true,
  },
  {
    name: "dash-text-q3-2021",
    payment_amount: 65,
    url: "https://www.dashcentral.org/p/dash-text-q3-2021",
    AbsoluteYesCount: 232,
    YesCount: 294,
    NoCount: 62,
    AbstainCount: 5,
    fCachedEndorsed: false,
    fCachedFunding: false,
    passing: false,
    pastTrigger: false,
  },
  {
    name: "DashCoreGroupCompProposalAug_Nov",
    payment_amount: 2423,
    url: "https://www.dashcentral.org/p/DCGCompProposalAug_Nov",
    AbsoluteYesCount: 848,
    YesCount: 964,
    NoCount: 116,
    AbstainCount: 9,
    fCachedEndorsed: false,
    fCachedFunding: true,
    passing: true,
    pastTrigger: true,
  },
  {
    name: "DashDeliveryService",
    payment_amount: 35,
    url: "https://www.dashcentral.org/p/Dash-delivery-service",
    AbsoluteYesCount: 142,
    YesCount: 288,
    NoCount: 146,
    AbstainCount: 54,
    fCachedEndorsed: false,
    fCachedFunding: false,
    passing: false,
    pastTrigger: true,
  },
  {
    name: "DashNext2021-2",
    payment_amount: 75,
    url: "https://www.dashcentral.org/p/DashNext2021-2",
    AbsoluteYesCount: 533,
    YesCount: 562,
    NoCount: 29,
    AbstainCount: 9,
    fCachedEndorsed: false,
    fCachedFunding: false,
    passing: true,
    pastTrigger: true,
  },
  {
    name: "Dash-Core-Group-Legal-October-2021",
    payment_amount: 543,
    url: "https://www.dashcentral.org/p/DCG_Legal_Oct_2021",
    AbsoluteYesCount: 253,
    YesCount: 344,
    NoCount: 91,
    AbstainCount: 3,
    fCachedEndorsed: false,
    fCachedFunding: false,
    passing: false,
    pastTrigger: true,
  },
  {
    name: "DDVirtualVisa",
    payment_amount: 286,
    url: "https://www.dashcentral.org/p/DDVirtualVisa",
    AbsoluteYesCount: 810,
    YesCount: 812,
    NoCount: 2,
    AbstainCount: 9,
    fCachedEndorsed: false,
    fCachedFunding: false,
    passing: true,
    pastTrigger: true,
  },
  {
    name: "Dash-Help-Q4",
    payment_amount: 56,
    url: "https://www.dashcentral.org/p/Dash-Help-Q4",
    AbsoluteYesCount: 222,
    YesCount: 299,
    NoCount: 77,
    AbstainCount: 5,
    fCachedEndorsed: false,
    fCachedFunding: false,
    passing: false,
    pastTrigger: true,
  },
  {
    name: "Towers",
    payment_amount: 35,
    url: "https://www.dashcentral.org/p/Towers",
    AbsoluteYesCount: 613,
    YesCount: 651,
    NoCount: 38,
    AbstainCount: 12,
    fCachedEndorsed: false,
    fCachedFunding: true,
    passing: true,
    pastTrigger: true,
  },
  {
    name: "DIF-OCT2021-FUNDING",
    payment_amount: 500,
    url: "https://www.dashcentral.org/p/DIF-OCT2021-FUNDING",
    AbsoluteYesCount: 264,
    YesCount: 289,
    NoCount: 25,
    AbstainCount: 0,
    fCachedEndorsed: false,
    fCachedFunding: false,
    passing: false,
    pastTrigger: true,
  },
  {
    name: "DashElectrumOct2021",
    payment_amount: 52,
    url: "https://www.dashcentral.org/p/DashElectrumOct2021",
    AbsoluteYesCount: 298,
    YesCount: 312,
    NoCount: 14,
    AbstainCount: 0,
    fCachedEndorsed: false,
    fCachedFunding: false,
    passing: false,
    pastTrigger: true,
  },
  {
    name: "dash-marketing-hub-2",
    payment_amount: 100,
    url: "https://www.dashcentral.org/p/dash-marketing-hub-2",
    AbsoluteYesCount: 202,
    YesCount: 262,
    NoCount: 60,
    AbstainCount: 52,
    fCachedEndorsed: false,
    fCachedFunding: false,
    passing: false,
    pastTrigger: true,
  },
];

export default proposals;
